# Generated by Django 4.0.6 on 2022-07-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('main', models.CharField(max_length=50, verbose_name='주연')),
                ('years', models.IntegerField(verbose_name='개봉 년도')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('starRating', models.FloatField(verbose_name='별점')),
                ('runningTime', models.IntegerField(verbose_name='러닝타임')),
                ('reviews', models.TextField(verbose_name='리뷰 내용')),
            ],
        ),
    ]
